version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - ./app/database/init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./app/database/data.sql:/docker-entrypoint-initdb.d/02-data.sql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - db